# Generated by Django 5.1.6 on 2025-02-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_reserva_comentarios_remove_reserva_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='nombre',
            new_name='nombre_cliente',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cliente',
        ),
        migrations.AddField(
            model_name='reserva',
            name='mesa',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
